language: python
python:
    - "3.8"
script: python parse_wortliste_wien.py -g ":" -b nein -o worttabelle.csv -i ignor_liste.txt -l my-list.txt -w gender_liste.dic -f fehler_woerter.txt
deploy:
    provider: releases
    api_key:
        secure: CI_API_KEY_ENCRYPTED
    file: 
        - gender_liste.dic
        - fehler_woerter.txt
    skip_cleanup: true
    on:
        tags: true    