language: python
python:
- '3.8'
script: python parse_wortliste_wien.py -g ":" -b nein -o worttabelle.csv -i ignor_liste.txt
  -l my-list.txt -w gender_liste.dic -f fehler_woerter.txt
deploy:
  provider: releases
  api_key:
    secure: OTUbOK/Du7Ml4uj8u1RPVDQt/qzDDEDGgiRtebADJ9Qe5t2TFW8DV6NYIr31HHwSWpMbadz3PoMMLQrECyHs+6tjsuyyx3Uc3Y0pYcRYV0kf2XvrmJlrPwRe9133TAGdPKm3GfiJCZmGGGTFHZ/pggCBjZBgZjH26ADikC7/z2JA2iiPYon4G+kTTxPQJFVc4qJ3vr9eZLWNrSEL3Cuj58E9wCh2JVBRejsOJa69qU78AUw4/BikMJGhvMQ07LWVJ2uey9tqLEqXBL4FC5WPFgdZkpZSv/MP0gBfUEzVM3f9a49dh9rUl4ZLMuS4SO5BLG9BpJSvKiLr5NEdB7gqoxfaSDLkwN0EWi7Kt+cRaNj41aoVLrTtBVtrHiHQknl2L6arX+nSk4Hb9yRtIYOcImrnlfooyx/49oip2/4oDj6wLbR+BA9/2jNAOe29zwk+HEWlTf7Z+6zUBOUcS5H8e1+WKqrbYvcX4rSt+LyWyCwdN9QZ0KC0q+mXUkpglqlQsq9p6weHzBLTJUxgK3fadr2Rq0c9rKmGDlUsv1pjAlQyZTbbt1SvmB7yBCML2nM6ZisIzD02ux2D4mf6wsLY2qcZEVFNMqt7+s2B8LhOxzDHn4ICa1Cp4xMe1j1+nFbGthvsIOZ+LfMEcPhqSptNwE+r9AkkLGYGfMgO9NB6T8s=
  file: gender_liste.dic
  on:
    repo: AndreasGocht/GenderListe
  skip_cleanup: 'true'
